## **NUMPY Exercise**
---

In [2]:
import numpy as np
import sys

In [3]:
print(np.__version__)

1.26.4


### **Array creation**

#### Q1) create a numpy array of size 10, filled with 0s

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Q2) Create a numpy array with values ranging from 10 to 49

In [5]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Q3) Create a numpy matrix of 2*2 integers, filled with ones.

In [6]:
np.ones((2,2),dtype=int)

array([[1, 1],
       [1, 1]])

#### Q4) Create a numpy matrix of 3*2 float numbers, filled with ones.

In [7]:
np.ones((3,2),dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

#### Q5) Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [8]:
X = np.arange(4, dtype=int)
# creates a new NumPy array of the same shape and data type as x, but filled with ones (1s).
np.ones_like(X)

array([1, 1, 1, 1])

#### Q6) Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [9]:
Y = np.array([[1,2,3],[4,5,6]],dtype=int)
np.zeros_like(Y)

array([[0, 0, 0],
       [0, 0, 0]])

#### Q7) Create a numpy matrix of 4*4 integers, filled with fives.

In [10]:
np.ones((4,4),dtype=int)*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

#### Q8) Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [11]:
Z = np.array([[1,2,3],[4,5,6]],dtype=int)
np.ones_like(Z)*7

array([[7, 7, 7],
       [7, 7, 7]])

#### Q9) Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [12]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### Q10) Create a numpy array, filled with 3 random integer values between 1 and 10.

In [13]:
np.random.randint(1,10,3)

array([4, 4, 7])

#### Q11) Create a 3 * 3 * 3 numpy matrix, filled with random float values.

In [14]:
np.random.random((3,3,3))

array([[[0.16113006, 0.1249522 , 0.93183664],
        [0.50510278, 0.85279529, 0.25702002],
        [0.69708718, 0.62618012, 0.47063007]],

       [[0.81078214, 0.69252376, 0.67338534],
        [0.22807568, 0.23292411, 0.46005022],
        [0.82230767, 0.86269645, 0.12990689]],

       [[0.66348065, 0.21965307, 0.86778923],
        [0.68603018, 0.08899183, 0.56621504],
        [0.9990092 , 0.58747062, 0.72603349]]])

#### Q12) Given the X python list convert it to an Y numpy array

In [15]:
X = [1,2,3,4,5]
print(type(X))
Y = np.array(X)
print(type(Y))

<class 'list'>
<class 'numpy.ndarray'>


#### Q13) Given the X numpy array, make a copy and store it on Y.

In [16]:
X = np.array([1,2,3,4,5])
Y = np.array(X) # we can create a copy in this way
# Y = np.copy(X) # we can also create a copy using this way
X is Y # False because they are different objects 

False

#### Q14) Create a numpy array with numbers from 1 to 10

In [17]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Q15) Create a numpy array with the odd numbers between 1 to 10

In [18]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

#### Q16) Create a numpy array with numbers from 1 to 10, in descending order.

In [19]:
np.arange(1,11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

#### Q17) Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [20]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Q18) Show the memory size of the given Z numpy matrix

In [21]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


### **Array indexation**

#### Q19) Given the X numpy array, show it's first element

In [22]:
X = np.arange(10)
X

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
X[0]

0

#### Q20) Given the X numpy array, show it's last element

In [24]:
X[-1]

9

#### Q21) Given the X numpy array, show it's first three elements

In [25]:
X[:3]

array([0, 1, 2])

#### Q22) Given the X numpy array, show all middle elements

In [26]:
X[1:-1]

array([1, 2, 3, 4, 5, 6, 7, 8])

#### Q23) Given the X numpy array, show the elements in reverse position

In [30]:
X[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### Q24) Given the X numpy array, show the elements in an odd position

In [31]:
X[1::2]

array([1, 3, 5, 7, 9])

#### Q25) Given the X numpy matrix, show the first row elements

In [33]:
Y = np.arange(9).reshape(3,3)
Y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
Y[0]

array([0, 1, 2])

#### Q26) Given the X numpy matrix, show the last row elements

In [35]:
Y[-1]

array([6, 7, 8])

#### Q27) Given the X numpy matrix, show the first element on first row

In [39]:
Y[0][0]
# or Y[0,0]

0

#### Q28) Given the X numpy matrix, show the last element on last row

In [40]:
Y[-1,-1]

8

#### Q29) Given the X numpy matrix, show the middle row elements

In [44]:
Y[1:-1]

array([[3, 4, 5]])

#### Q30) Given the X numpy matrix, show the middle row middle elements

In [47]:
# Y[1:-1][1:-1]
Y[1:-1,1:-1]

array([[4]])

#### Q31) Given the X numpy matrix, show the first two elements on the first two rows

In [48]:
Y[:2,:2]

array([[0, 1],
       [3, 4]])

#### Q32) Given the X numpy matrix, show the last two elements on the last two rows

In [51]:
Y[-2:,-2:]
# Y[2:, 2:]

array([[4, 5],
       [7, 8]])

### **Array manipulation**

#### Q33) Convert the given integer numpy array to float

In [54]:
Z = np.arange(10)
Z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
np.array(Z,dtype = float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### Q34) Reverse the given numpy array (first element becomes last)

In [56]:
Z[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### Q35) Order (sort) the given numpy array

In [58]:
X = np.array([8,5,7,6,1,2,9,10,3])
X

array([ 8,  5,  7,  6,  1,  2,  9, 10,  3])

In [61]:
# note that .sort function is used to sort the array in ascending order 
# np.sort() only sorts in ascending order, but you can reverse it using [::-1]:
np.sort(X)

array([ 1,  2,  3,  5,  6,  7,  8,  9, 10])

#### Q36) Given the X numpy array, set the fifth element equal to 1

In [63]:
X[5] = 1
X

array([ 8,  5,  7,  6,  1,  1,  9, 10,  3])

#### Q37) Given the X numpy array, change the 50 with a 40

In [64]:
X = np.array([10, 20 , 30 , 50 , 60])
X

array([10, 20, 30, 50, 60])

In [65]:
X[X == 50] = 40
X

array([10, 20, 30, 40, 60])

#### Q38) Given the X numpy matrix, change the last row with all 1

In [66]:
X = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
X

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [68]:
X[-1] = 1
X

array([[10, 20, 30],
       [40, 50, 60],
       [ 1,  1,  1]])

#### Q39) Given the X numpy matrix, change the last item on the last row with a 0

In [69]:
X[-1,-1] = 0
X

array([[10, 20, 30],
       [40, 50, 60],
       [ 1,  1,  0]])

#### Q40) Given the X numpy matrix, add 5 to every element

In [70]:
X[:] = 5
X

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

### **Boolean arrays (also called masks)**

#### Q41) Given the X numpy array, make a mask showing negative elements

In [71]:
Y = np.array([8,9,12,1,-5,20,-7,23,-10])
Y

array([  8,   9,  12,   1,  -5,  20,  -7,  23, -10])

In [73]:
mask = Y < 0
mask

array([False, False, False, False,  True, False,  True, False,  True])

#### Q42) Given the X numpy array, get the negative elements

In [74]:
negNo = Y[Y < 0]
negNo

array([ -5,  -7, -10])

#### Q43) Given the X numpy array, get numbers higher than 5

In [76]:
Y[Y > 5]

array([ 8,  9, 12, 20, 23])

#### Q44) Given the X numpy array, get numbers higher than the elements mean

In [78]:
Y[Y > Y.mean()]

array([ 8,  9, 12, 20, 23])

#### Q45) Given the X numpy array, get numbers equal to 2 or 10

In [79]:
X = np.array([5,8,1,3,2,4,10,89])
X

array([ 5,  8,  1,  3,  2,  4, 10, 89])

In [83]:
X[ (X == 2) | (X == 10) ]

array([ 2, 10])

### **Logic Functions**

#### Q46) Given the X numpy array, return True if none of its elements is zero

In [91]:
X = np.array([10,45,0,18,0,23,0,17])
X

array([10, 45,  0, 18,  0, 23,  0, 17])

In [95]:
# Returns True if all elements in the input array a evaluate to True. Otherwise, it returns False.
X.all()

False

#### Q47) Given the X numpy array, return True if any of its elements is zero

In [96]:
# Returns True if at least one element in the input array a evaluates to True. If all elements are False or the array is empty, it returns False.
X.any()

True

### **Summary statistics**

#### Q48) Given the X numpy array, show the sum of its elements

In [97]:
Y = np.arange(1,10)
Y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
Y.sum()

45

#### Q49) Given the X numpy array, show the mean value of its elements

In [99]:
Y.mean()

5.0

#### Q50) Given the X numpy matrix, show the sum of its columns

In [100]:
Z =  np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
Z

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [102]:
Z.sum(axis = 0)

array([28, 32, 36, 40])

#### Q51) Given the X numpy matrix, show the mean value of its rows

In [103]:
Z.mean(axis = 1)

array([ 2.5,  6.5, 10.5, 14.5])

#### Q52) Given the X numpy array, show the max value of its elements

In [104]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])
X

array([ 1,  2,  0,  4,  5,  6,  0,  0,  9, 10])

In [106]:
X.max()

10

#### **END PRACTICE**